spring:
  application:
    name: api-users


  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:users_db}}
    username: ${DB_USER:test}
    password: ${DB_PASSWORD:testpw}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
server:
  port: 8080
